#ifndef __SETTINGS_H__
#define __SETTINGS_H__

#define DEBUG_REQUEST_IP_ADDRESS false
#define DEBUG_INCOMING_REQUEST_VERBOSELY false
#define DEBUG_REQUEST_HANDLER true

#define SINGLE_THREAD true
#define THREAD_POOL_SIZE 10

#define SERVER_PORT 8080
#define MAXLINE 1024

#endif